setwd("~/Documents/Class_data/MechaCar_Statistical_Analysis")
library(dplyr)
MechaCar_mpg <- read.csv(file ='MechaCar_mpg.csv')
head(MechaCar_mpg)
lm(mpg~ vehicle_length + spoiler_angle + vehicle_weight + ground_clearance + AWD, data=MechaCar_mpg)
summary(mpg~ vehicle_length + spoiler_angle + vehicle_weight + ground_clearance + AWD, data=MechaCar_mpg)

setwd("~/Documents/Class_data/MechaCar_Statistical_Analysis")
suspension_coil <- read.csv(file ='Suspension_Coil.csv')
head(suspension_coil)
library(tidyverse)
total_summary <- suspension_coil %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
lot_summary <- suspension_coil %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
t.test(suspension_coil$PSI, mu=mean(1500))
?t.test()
t.test(subset(suspension_coil$PSI, suspension_coil$Manufacturing_Lot == "Lot1"), mu=mean(suspension_coil$PSI))
t.test(subset(suspension_coil$PSI, suspension_coil$Manufacturing_Lot == "Lot2"), mu=mean(suspension_coil$PSI))
t.test(subset(suspension_coil$PSI, suspension_coil$Manufacturing_Lot == "Lot3"), mu=mean(suspension_coil$PSI))
